import {config} from 'dotenv'

config({
    path: '.env'
});

export const {DB_URI,TEST_DB_URI,PORT,JWT_EXPIRES_IN,JWT_SECRET,ARCJET_KEY,NODE_ENV,QSTASH_TOKEN,QSTASH_URL,QSTASH_CURRENT_SIGNING_KEY,QSTASH_NEXT_SIGNING_KEY,SERVER_URL,EMAIL_USER,EMAIL_PASSWORD} = process.env;
